"""Relacionar payments con purchase

Revision ID: 025c5f393f69
Revises: 23ae7ae6fd15
Create Date: 2025-05-15 15:44:53.468372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025c5f393f69'
down_revision = '23ae7ae6fd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('offer_id', sa.Integer(), nullable=False),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column('purchase_date', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="created_at::timestamp without time zone")  # Agregado el USING aquí
        batch_op.create_foreign_key(None, 'purchases', ['purchase_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('purchase_id')

    op.drop_table('purchases')
    # ### end Alembic commands ###
