"""empty message

Revision ID: 0f0d47ce333e
Revises: d07d59c4c351
Create Date: 2025-04-16 18:14:19.832613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0d47ce333e'
down_revision = 'd07d59c4c351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('companies_bussiness_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('bussiness_email')
        batch_op.drop_column('company_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bussiness_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('companies_bussiness_email_key', ['bussiness_email'])
        batch_op.drop_column('status')
        batch_op.drop_column('slug')
        batch_op.drop_column('rating')
        batch_op.drop_column('country')
        batch_op.drop_column('website')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
