"""empty message

Revision ID: 158be4563402
Revises: 32b13d0a5d6e
Create Date: 2025-05-10 07:41:28.522001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158be4563402'
down_revision = '32b13d0a5d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suscription', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('suscription')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
