"""empty message

Revision ID: 23ae7ae6fd15
Revises: 6723a7356bcf
Create Date: 2025-05-11 01:24:18.238373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ae7ae6fd15'
down_revision = '6723a7356bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suscription', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('suscription')

    # ### end Alembic commands ###
