"""Add cardholder_name to payments

Revision ID: 49282dfdb60e
Revises: 025c5f393f69
Create Date: 2025-05-16 12:13:16.883514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49282dfdb60e'
down_revision = '025c5f393f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardholder_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('card_number')
        batch_op.drop_column('cardholder_name')

    # ### end Alembic commands ###
