"""empty message

Revision ID: 8e463ce99eaa
Revises: 0ae774768eae
Create Date: 2025-05-09 10:41:48.771101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e463ce99eaa'
down_revision = '0ae774768eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagedetails1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagedetails2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagedetails3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagedetails4', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('imagedetails4')
        batch_op.drop_column('imagedetails3')
        batch_op.drop_column('imagedetails2')
        batch_op.drop_column('imagedetails1')

    # ### end Alembic commands ###
