"""empty message

Revision ID: bf4c5cd4b47e
Revises: 7c39da691c49
Create Date: 2025-04-20 01:14:59.530641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4c5cd4b47e'
down_revision = '7c39da691c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint('offers_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('type_offert')
        batch_op.drop_column('company_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_offert', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('offers_company_id_fkey', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
